### PR TITLE
Additional current menu item indications

### LINKED ISSUE #61: Add main menu current indication when sub-menu item is current
Look at enabling the current link underline for a sub-menu parent when a sub-menu link is current.

### PR DESCRIPTION
**Pull request by Misplon**
* Indicate a current sub-menu item by changing the sub-menu link color to the hover color.
* Show the top level menu item indication (border-bottom) when a sub-menu item is current.

Resolves #61.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
> Indicate a current sub-menu item by changing the sub-menu link color to the hover color.

This works for me.

> Show the top level menu item indication (border-bottom) when a sub-menu item is current.

This isn't. Looks like the `:not(.current-page-ancestor)` isn't applying correctly.

**Comment by Misplon** [comment]
Do you have a menu assigned?

**Comment by AlexGStapleton** [comment]
I do. I tried creating a few different submenus and can't get `current-page-ancestor` to output. I do however always have `current_page_ancestor` present.

**Comment by Misplon** [comment]
Thanks, give that a try.

**Comment by Misplon** [comment]
Current link indication should now carry through multiple sub-menu items. 

I've done a build and tested it https://demo.siteorigin.com/corp/one-page-demo/. One page menu functionality looks good (not impacted).

**Comment by AlexGStapleton** [comment]
Looks good! 👍

**Pull request merged**
