### PR TITLE
Jetpack portfolio

### PR DESCRIPTION
**Pull request by Misplon**
Adds Jetpack Portfolio support.

* Jetpack portfolio added via the Post Loop widget.
* Jetpack portfolio accessed via the /portfolio/ URL.
* Archive pages for project types and tags.
* Infinite scroll support for the above.
* Support for the Jetpack [portfolio] short tag up to 6 columns.

@AlexGStapleton Please, test all of the above. When checking responsive layouts, be sure to scroll down at 768 and 480. For the shortcode that'll be for the 6 different layout options available. [portfolio columns=1],  [portfolio columns=2] etc.

### CODE REVIEW

**Comment by AlexGStapleton** [comment]
When I add the exact number of portfolio items allowed per page (10), pagination is setup but the next page is completely blank. This is happening for me with both the portfolio archive and post loop.



Can the Portfolio items per page be reduced by one or increased by two by default? I ask as ten is an odd number for a three column setup



I can't seem to get Infinite scroll to work for Portfolio items. Is there anything, outside of enabling Infinite Scroll, that I need enable?

--

Regarding the portfolio shortcode, when `[portfolio columns=3]` is used the third column is red:



Relavent CSS found in style.min.css:

```
.jetpack-portfolio-shortcode .portfolio-entry.portfolio-entry-column-3:nth-child(3n+3) {
    background: red;
    margin-right: 0;
}
```

When [portfolio columns=1] collapses for tablets, it should really retain the one column structure rather than increasing to two columns. It may also be a good idea to collapse larger column portfolio sooner rather than later as 6 columns at 1024 (which is an iPad in landscape) doesn't look very good:

**Comment by Misplon** [comment]
**When I add the exact number of portfolio items allowed per page (10), pagination is setup but the next page is completely blank. This is happening for me with both the portfolio archive and post loop.**

Will check.

**Can the Portfolio items per page be reduced by one or increased by two by default? I ask as ten is an odd number for a three column setup**

The setting is located at Settings > Writing. It'll be up to the user to adjust to 9 or a setting they prefer.

**Regarding the portfolio shortcode, when [portfolio columns=3] is used the third column is red:**

Resolved.

**I can't seem to get Infinite scroll to work for Portfolio items. Is there anything, outside of enabling Infinite Scroll, that I need enable?**

Nothing in particular, not sure why that isn't working for you yet.

**When [portfolio columns=1] collapses for tablets, it should really retain the one column structure rather than increasing to two columns. It may also be a good idea to collapse larger column portfolio sooner rather than later as 6 columns at 1024 (which is an iPad in landscape) doesn't look very good:**

Will do.

**Comment by AlexGStapleton** [comment]
> The setting is located at Settings > Writing. It'll be up to the user to adjust to 9 or a setting they prefer.

Are you referring to the **Blog pages show at most** setting? If so, that's not working for me. Mine was set to 5 before I started testing and it was always outputting 10 items for me.

**Comment by Misplon** [comment]
Writing_Settings_‹_SiteOrigin_—_WordPress

**Comment by AlexGStapleton** [comment]
Yeah, I don't see that. Hm. Oh... I think it might be because I'm running Jetpack in development mode. That's a really strange limitation if that's the reason why I'm not seeing it.

**Comment by Misplon** [comment]
It's there for me in Development Mode.

**Comment by Misplon** [comment]
When I add the exact number of portfolio items allowed per page (10), pagination is setup but the next page is completely blank. This is happening for me with both the portfolio archive and post loop.
<hr>
I don't seem to be able to re-create that in either the Post Loop widget or the archive page. I'm not sure why.

When [portfolio columns=1] collapses for tablets, it should really retain the one column structure rather than increasing to two columns. It may also be a good idea to collapse larger column portfolio sooner rather than later as 6 columns at 1024 (which is an iPad in landscape) doesn't look very good
<hr>
Should be fixed now. Please, take a look. Thanks.

**Comment by AlexGStapleton** [comment]
Reinstalled Jetpack and re-added the development configuration and I'm now seeing the Portfolio Project settings at **WP Admin > Settings > Writing**.

**I don't seem to be able to re-create that in either the Post Loop widget or the archive page. I'm not sure why.**
I've run a few tests and this only happens when the **Portfolio pages display at most X projects** setting is set to the _exact_ number of projects you have. Anything else will prevent this issue from occurring.

Shortcode and infinite Scroll look good.

**Comment by Misplon** [comment]
Super, thanks for the feedback.

I don't seem to be able to recreate the empty pagination issue. We're using `the_posts_pagination` as we do for the other loops. I'm ok with leaving this for the moment and re-looking at it if it gets raised. Thanks again.

**Pull request merged**
