### PR TITLE
WC: Custom Variation Select Arrow

### PR DESCRIPTION
**Pull request by AlexGStapleton**
Resolve https://github.com/siteorigin/siteorigin-corp/issues/163

Arrow placement will need to be adjusted. The existing select sizing is browser dependent so a specific set of cross-browser sizing will need to be decided.

### CODE REVIEW

**Comment by Misplon** [comment]
Thanks, mate. What do you think about using the same icon we're using for the drop-down on the WC archive page?

**Comment by AlexGStapleton** [comment]
Done. Didn't know that had a custom icon already or I would have used that from the get-go.

**Comment by AlexGStapleton** [comment]
Sorry about that. Fixed in the last commit. I've uploaded a build with that fix present.

**Comment by Misplon** [comment]
No worries! Thanks.

**Comment by AlexGStapleton** [comment]
How does that look?  The last two commits add support for the Clear button and add the Corp drop down to the Quick View.

**Comment by Misplon** [comment]
Super, thanks mate.

It looks like if you re-open the quick view the select fields are re-added on each open.

Products_Archive_-_Corp

**Review by Misplon — APPROVED** [review]

**Pull request merged**
