### PR TITLE
Avoid always showing mobile menu scroll bar in FF and IE

### PR DESCRIPTION
**Pull request by Misplon**
Ref #52. The issue doesn’t seem to persist in Safari regardless of the scroll value. I see the issue in FF and I guess it’s there in IE.

### CODE REVIEW

**Comment by Misplon** [comment]
Mmm, no I can't but I can't see any difference when I change it back. Try changing it back to `overflow-y: scroll`, do you see the scrollbar then?

**Comment by AlexGStapleton** [comment]
I don't see it when I change it back. I guess it never actually appeared. 😕

**Comment by Misplon** [comment]
@AlexGStapleton Can you take a look now? Styling added for the scrollbar in Chrome (and Safari). The issue seems to be resolved in FF, no FF styling though.

**Comment by AlexGStapleton** [comment]
The issue is resolved in FireFox and no styling either. I'm pretty sure FireFox requires the moz prefix.

**Comment by Misplon** [comment]
I don't know that there is a FF equivalent: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar Do you see one?

**Comment by AlexGStapleton** [comment]
Chrome works, but I can't see any sort of scrollbar there either. 😕

**Comment by Misplon** [comment]
https://medium.com/@beraliv/scrollbar-customisation-31bd28652e9
Gecko
Nothing yet available. The bug was reported 18 years ago and is still in progress. Wow 😔.
Firefox, sorry for making it impossible to fully customise scrollbar for you.

**Comment by AlexGStapleton** [comment]
Ah. I was mistaken, no FireFox support. https://bugzilla.mozilla.org/show_bug.cgi?id=547260

**Comment by Misplon** [comment]
Cool, done. Not going into JS for this.

**Pull request merged**
